name: Auto-add Issues to Project V2 and Set Status

on:
  issues:
    types: [labeled]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write      # Allows modifying issue labels and content
      contents: read     # Allows reading the content of the repo

    steps:
      - name: Add issue to project and update status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const label = context.payload.label.name;

            const labelToStatus = {
              "in progress": "47fc9ee4",
              "blocked": "c6d9dc00",
              "ready for review": "c028b65f",
              "done": "98236657",
              "bug": "f75ad846", // send bugs to Todo (Ready)
              "enhancement": "84efa04b", // Backlog
              "question": "d19063af" // Notes
            };

            const projectId = "PVT_kwHOBcYL5M4A3sd8";
            const statusFieldId = "PVTSSF_lAHOBcYL5M4A3sd8zgsycoA";

            const statusOptionId = labelToStatus[label.toLowerCase()];
            if (!statusOptionId) {
              console.log("Label not mapped to a status, skipping.");
              return;
            }

            const item = await github.graphql(`
              mutation($projectId:ID!, $contentId:ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `, {
              projectId,
              contentId: issue.node_id
            });

            const itemId = item.addProjectV2ItemById.item.id;

            await github.graphql(`
              mutation($projectId:ID!, $itemId:ID!, $fieldId:ID!, $optionId:String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: {
                    singleSelectOptionId: $optionId
                  }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              projectId,
              itemId,
              fieldId: statusFieldId,
              optionId: statusOptionId
            });

            console.log(`Issue added to project and status set to ${label}`);
